version: "3"

services:
  mysql-8.0.31:
    image: docker.io/mysql:8.0.31
    restart: always
    ports:
      - "33060:3306"
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}

    volumes:
      - mysql-8.0.31-data:/var/lib/mysql

    deploy:
      resources:
        limits:
          memory: ${DATABASE_MEM_LIMIT}

  phpmyadmin-5.2.1:

    image: docker.io/phpmyadmin:5.2.1
    restart: always

    ports:
      - ${PHPMYADMIN_PUBLIC_PORT}:${PHPMYADMIN_LOCAL_PORT}

    environment:
      - PMA_HOST=mysql-8.0.31
      - UPLOAD_LIMIT=200M

    deploy:
      resources:
        limits:
          memory: ${PHPMYADMIN_MEM_LIMIT}

    depends_on:
      - mysql-8.0.31


volumes:
  mysql-8.0.31-data: {}

networks:
  default:
    driver: bridge